### PR TITLE
Minor fixes to isempty for v6

### LINKED ISSUE #14: Empty template has some left-overs from v5
I've noticed that the isempty template still has a few stray references to v5, including:

- A link to v5 of the docs 
- A comment refers to MVC, but the template has changed to razor pages
- The commented out "uncomment to add UI" snippet in ConfigureServices isn't updated to use the builder argument (should reference  `builder.Services` instead of `services`

### PR DESCRIPTION
**Pull request by josephdecock**
- Fixed call to AddRazorPages
- Fixed a link to v5 documentation

Fixes #14

### CODE REVIEW

File: build/Program.cs [hunk 1]
```diff
@@ -7,7 +7,7 @@ namespace build
 {
     internal static class Program
     {
-        private const string NugetPackageVersion = "6.0.0";
+        private const string NugetPackageVersion = "6.0.1";
```
Comment (josephdecock) [inline build/Program.cs:10]: Is this correct/sufficient to release an updated patch version?

File: src/IdentityServerEmpty/HostingExtensions.cs [hunk 2]
```diff
@@ -6,12 +6,12 @@ internal static class HostingExtensions
...
     {
-        // uncomment, if you want to add an MVC-based UI
-        //services.AddRazorPages();
+        // uncomment if you want to add a UI
+        //builder.services.AddRazorPages();
 
         builder.Services.AddIdentityServer(options =>
             {
-                // https://docs.duendesoftware.com/identityserver/v5/fundamentals/resources/
+                // https://docs.duendesoftware.com/identityserver/v6/fundamentals/resources/api_scopes#authorization-based-on-scopes
```
Comment (josephdecock) [inline src/IdentityServerEmpty/HostingExtensions.cs:14]: Updating the link to v6, and also moving the link deeper into the docs, closer to where the audience claim is discussed

**Comment by leastprivilege** [comment]
Great! Thanks!
